name: budget_manager
description: A new Flutter project.

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_inner_drawer: ^0.5.7+2
  fl_chart: ^0.12.0
  provider: ^4.1.3
  path_provider: ^1.6.21
  sqflite: ^1.3.1+2
  fluttertoast: ^7.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  assets:
    - lib/assets/

  uses-material-design: true
